# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.4.0-rc1
      import: true

    - name: libknx
      url: https://gitlab.knx.org/public-projects/knx-iot-point-api/knx-iot-point-api-stack.git
      revision: nxp_zephyr_port_experimental
      path: modules/lib/libknx
      submodules:
        - path: deps/tinycbor
